version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=9mREsvXDs9Gk89Ef
volumes:
  db-data: